name       : sshguard
version    : 2.3.1
release    : 4
source     :
    - https://netcologne.dl.sourceforge.net/project/sshguard/sshguard/2.3.1/sshguard-2.3.1.tar.gz : 769055e26df78f4bca34c9a7acf265dfa224c055b33ced47f53d55bf659d20a2
license    :
    - BSD-3-Clause
    - ISC
    - Public-Domain
component  : network.util
summary    : SSH Server attack protection again SSH and other services.
description: |
    SSHGuard protects hosts from brute-force attacks against SSH and other services. It aggregates system logs and blocks repeat offenders using several firewall backends, including iptables, ipfw, and pf.
rundeps    :
    - firewalld
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 $pkgfiles/sshguard.service $installdir/%libdir%/systemd/system/sshguard.service
    install -Dm00644 $pkgfiles/sshguard.conf $installdir/etc/sshguard.conf
check      : |
    %make check
