name       : sshguard
version    : 2.0.0
release    : 1
source     :
    - https://ncu.dl.sourceforge.net/project/sshguard/sshguard/2.0.0/sshguard-2.0.0.tar.gz : e87c6c4a6dddf06f440ea76464eb6197869c0293f0a60ffa51f8a6a0d7b0cb06
license    : ISC
component  : network.util
summary    : SSH Server attack protection again SSH and other services.
description: |
    SSHGuard protects hosts from brute-force attacks against SSH and other services. It aggregates system logs and blocks repeat offenders using several firewall backends, including iptables, ipfw, and pf.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
